# Generated by Django 4.2.7 on 2023-11-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_hashtag_alter_post_content_alter_post_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="jpeg", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(
                blank=True, to="blog.hashtag", verbose_name="Хештег"
            ),
        ),
    ]
