# Generated by Django 4.2.7 on 2023-11-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_image_alter_post_hashtag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="Название")),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="gallery",
                        verbose_name="Изображение",
                    ),
                ),
                ("slug", models.SlugField()),
            ],
        ),
    ]
